name: VM

on:
  push:

env:
  DOTNET_VERSION: 8.0.x

jobs:
  vm:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Brew
      run: |
        brew install leveldb
        brew install wget
        mkdir -vp ./bin/runtimes/osx-arm64/native
        wget https://github.com/neo-ngd/leveldb/releases/download/v1.23/libleveldb-osx-arm64.zip
        unzip libleveldb-osx-arm64.zip
        cp -vp libleveldb-osx-arm64/libleveldb.dylib ./bin/runtimes/osx-arm64/native/libleveldb.dylib
        dotnet test ./tests/Neo.Plugins.Storage.Tests/Neo.Plugins.Storage.Tests.csproj
