name: VM

on:
  push:

env:
  DOTNET_VERSION: 8.0.x

jobs:
  vm:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Brew
      run: |
        brew install leveldb
        mkdir -vp ./src/Plugins/LevelDBStore/runtimes/win-x64/native
        mkdir -vp ./src/Plugins/LevelDBStore/runtimes/win-arm64/native
        mkdir -vp ./src/Plugins/LevelDBStore/runtimes/osx-x64/native
        mkdir -vp ./src/Plugins/LevelDBStore/runtimes/osx-arm64/native

        wget https://github.com/neo-ngd/leveldb/releases/download/v1.23/libleveldb-win-x64.zip
        unzip libleveldb-win-x64.zip
        cp -vp libleveldb-win-x64/libleveldb.dll ./src/Plugins/LevelDBStore/runtimes/win-x64/native/libleveldb.dll

        wget https://github.com/neo-ngd/leveldb/releases/download/v1.23/libleveldb-win-arm64.zip
        unzip libleveldb-win-arm64.zip
        cp -vp libleveldb-win-arm64/libleveldb.dll ./src/Plugins/LevelDBStore/runtimes/win-arm64/native/libleveldb.dll

        wget https://github.com/neo-ngd/leveldb/releases/download/v1.23/libleveldb-osx-x64.zip
        unzip libleveldb-osx-x64.zip
        cp -vp libleveldb-osx-x64/libleveldb.dylib ./src/Plugins/LevelDBStore/runtimes/osx-x64/native/libleveldb.dylib

        wget https://github.com/neo-ngd/leveldb/releases/download/v1.23/libleveldb-osx-arm64.zip
        unzip libleveldb-osx-arm64.zip
        cp -vp libleveldb-osx-arm64/libleveldb.dylib ./src/Plugins/LevelDBStore/runtimes/osx-arm64/native/libleveldb.dylib

        dotnet build ./src/Plugins/LevelDBStore
        ls -la ./src/Plugins/LevelDBStore/runtimes/osx-arm64/native
        dotnet build ./tests/Neo.Plugins.Storage.Tests/Neo.Plugins.Storage.Tests.csproj
        ls -la tests/Neo.Plugins.Storage.Tests/bin/Debug/net8.0/runtimes/osx-arm64/native
        dotnet test ./tests/Neo.Plugins.Storage.Tests/Neo.Plugins.Storage.Tests.csproj
